### ISSUE TITLE
Application fails on boards without EDBG circuits

### ISSUE THREAD

**Issue by michaesc** [MicrochipTech/atsamr34_long_range_p2p#1]
It seems this firmware requires a second (EDBG) MCU, which has nothing to do with the SAMR34:

```
src/main.c:
void ReadMacAddress(void)
{
#if (BOARD == SAMR34_XPLAINED_PRO && defined(__SAMR34J18B__))
        uint8_t* peui64 = edbg_eui_read_eui64() ;
```

Other problems are that the EDBG code calls I2C commands, which also have nothing to do with the SAMR34.

```
src/ASF/thirdparty/wireless/services/edbg_eui/edbg-eui.c:
uint8_t *
edbg_eui_read_eui64(void)
{
  int timeout2 = 0;
  bool random_mac_address = false;
  uint8_t edbg_status = 0xFF;
  struct i2c_master_config config_i2c_master;

```

It's unclear why the README.md indicates an easy to use 'less than 30 lines' application which in fact fails on all the SAMR34 boards in the world except those that have a second EDBG MCU and I2C circuits. These things are often useless in real world user designs (as ours clearly shows.)

QUESTION

What changes do I need to make for this application to actually run on a ATSAMR34 board (with no NXP sensors, STM or other MCUs, and no extra circuits)?

SPEC

Our board exposes the SWD, RF, and UART circuits. It supplies 3V3 power to the SAMR34 MCU and routes a user button and two LEDs to GPIOs.

**Comment by gd91** [comment]
Added MACROs and comments in main.c
